### ISSUE TITLE
[Bug Report]: Composite ban fails if player is not online

### ISSUE THREAD

**Issue by pwnker** [A248/LibertyBans#117]
### LibertyBans Version

1.0

### I have confirmed that ...

- [X] LibertyBans is up to date
- [X] No similar issue has been reported

### Platform

Velocity 3.1.1 (online mode), MYSQL databse

### Description

When you try to punish a offline user with a composite ban, the ban is not completed, the command doesn't output anything and console shows the following error. 
```
Jan 10 09:39:04: [09:39:04 ERROR] [space.arim.libertybans.core.service.StandardAsynchronicityManager]: Exception during miscellaneous asynchronous computation
Jan 10 09:39:04: java.util.concurrent.CompletionException: org.jooq.exception.TooManyRowsException: Cursor returned more than one result
Jan 10 09:39:04:         at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
Jan 10 09:39:04:         at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
Jan 10 09:39:04:         at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
Jan 10 09:39:04:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
Jan 10 09:39:04:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
Jan 10 09:39:04:         at java.lang.Thread.run(Thread.java:833) [?:?]
Jan 10 09:39:04: Caused by: org.jooq.exception.TooManyRowsException: Cursor returned more than one result
Jan 10 09:39:04:         at org.jooq_3.15.1.MYSQL.debug(Unknown Source) ~[?:?]
Jan 10 09:39:04:         at org.jooq.impl.Tools.fetchOne(Tools.java:2325) ~[?:?]
Jan 10 09:39:04         at org.jooq.impl.ResultQueryTrait.fetchOne(ResultQueryTrait.java:506) ~[?:?]
Jan 10 09:39:04:         at org.jooq.impl.ResultQueryTrait.fetchOne(ResultQueryTrait.java:511) ~[?:?]
Jan 10 09:39:04:         at space.arim.libertybans.core.uuid.QueryingImpl.lambda$resolvePlayer$4(QueryingImpl.java:105) ~[?:?]
Jan 10 09:39:04:         at space.arim.libertybans.core.database.execute.SQLFunction$1.obtain(SQLFunction.java:42) ~[?:?]
Jan 10 09:39:04:         at space.arim.libertybans.core.database.execute.JooqQueryExecutor.obtainUnfailing(JooqQueryExecutor.java:69) ~[?:?]
Jan 10 09:39:04:         at space.arim.libertybans.core.database.execute.JooqQueryExecutor.lambda$query$0(JooqQueryExecutor.java:200) ~[?:?]
Jan 10 09:39:04:         at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
Jan 10 09:39:04:         ... 3 more```

**Comment by pwnker** [comment]
This only appears to affect players connected through floodgate.

**Comment by pwnker** [comment]
Seems to be an isssue with my foodgate config not liberty.

**Comment by BlueTree242** [comment]
ok ye would  you mind telling us what was the issue with floodgate config so other people can see the solution?

**Comment by pwnker** [comment]
I changed the floodgate prefix which must have messed with the ip resolution.

**Comment by A248** [comment]
Any exception in the server console is indicative of a bug (to a certain degree)

**Comment by pwnker** [comment]
I don't think this issue has been renamed correctly, after some more testing I have found it appears that on my installation you cannot ban or punish players while they are offline.

**Comment by A248** [comment]
You are correct. This happens when players have the same IP address.
