### ISSUE TITLE
[Bug Report]: Cant load plugin because of "Failed to download dependency"

### ISSUE THREAD

**Issue by honnisha** [A248/LibertyBans#193]
### LibertyBans Version

v1.1.0-M1

### I have confirmed that ...

- [X] LibertyBans is up to date
- [X] No similar issue has been reported

### Platform

Spigot/Paper

### Description

Ive got this error after last update:
I tried to delete folders internal and addons, but it not helped.
```[18:48:43] [Server thread/INFO]: [LibertyBans] Enabling LibertyBans v1.1.0-M1
[18:48:44] [Server thread/INFO]: [LibertyBans] No addons detected
[18:48:44] [Server thread/ERROR]: Error occurred while enabling LibertyBans v1.1.0-M1 (Is it up to date?)
java.util.concurrent.CompletionException: space.arim.libertybans.bootstrap.depend.BootstrapException: Failed to download dependency: Dependency [groupId=com.github.ben-manes.caffeine, artifactId=caffeine, version=3.1.2] . Reason: Hash mismatch, expected d6c71e7a621c81fc321fc12e394278c9ee978391089376568d376ae12bb66957293aa3d302eb849a391873c5468a30db422487f10f982ab6cb01923846691d37 but got a151f0db9cdd17612bc1d7ecb01dd65adc4720960edb9a6d48d11553e61f630446203e14f669c13336ee619bdef215872bf681a59a7470257ac217d97f73f39d
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: space.arim.libertybans.bootstrap.depend.BootstrapException: Failed to download dependency: Dependency [groupId=com.github.ben-manes.caffeine, artifactId=caffeine, version=3.1.2] . Reason: Hash mismatch, expected d6c71e7a621c81fc321fc12e394278c9ee978391089376568d376ae12bb66957293aa3d302eb849a391873c5468a30db422487f10f982ab6cb01923846691d37 but got a151f0db9cdd17612bc1d7ecb01dd65adc4720960edb9a6d48d11553e61f630446203e14f669c13336ee619bdef215872bf681a59a7470257ac217d97f73f39d
	at space.arim.libertybans.bootstrap.depend.BootstrapLauncher.loadJarPaths(BootstrapLauncher.java:64) ~[LibertyBans_Release-1.1.0-M1.jar:?]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
	... 5 more
[18:48:44] [Server thread/INFO]: [LibertyBans] Disabling LibertyBans v1.1.0-M1
[18:48:44] [Server thread/WARN]: [LibertyBans] LibertyBans wasn't launched; check your log for a startup error```

**Comment by A248** [comment]
This bug was fixed already, but you might have an older plugin jar. Re-download the latest version from SpigotMC/Github.

Please be careful with the `internal` directory. Your database is there.
