### ISSUE TITLE
[Support] DB Migration issue

### ISSUE THREAD

**Issue by FuchsFuchs1** [A248/LibertyBans#217]
### LibertyBans Version

LibertyBans version 1.1.0-M2

### I have confirmed that ...

- [X] LibertyBans is up to date
- [X] No similar issue has been reported

### Platform

Bungeecord

### Description

I was told in discord to make this a github issue
MY DB server is MariaDB

[18:17:19 ERROR] [space.arim.libertybans.core.database.DatabaseSettings]: Unable to migrate your database. Please create a backup of your database and promptly report this issue.
space.arim.libertybans.core.database.flyway.MigrationFailedException: org.flywaydb.core.api.exception.FlywayValidateException: Validate failed: Migrations have failed validation
Detected failed migration to version 24 (Add applicable history view). Please remove any half-completed changes then run repair to fix the schema history.
Need more flexibility with validation rules? Learn more: https://rd.gt/3AbJUZE
        at space.arim.libertybans.core.database.flyway.MigrateWithFlyway.migrate(MigrateWithFlyway.java:48) ~[?:?]
        at space.arim.libertybans.core.database.DatabaseSettings.create(DatabaseSettings.java:130) ~[?:?]
        at space.arim.libertybans.core.database.DatabaseSettings.create(DatabaseSettings.java:77) ~[?:?]
        at space.arim.libertybans.core.database.DatabaseManager.startup(DatabaseManager.java:86) ~[?:?]
        at space.arim.libertybans.core.LifecycleGodfather.startup0(LifecycleGodfather.java:77) ~[?:?]
        at space.arim.libertybans.core.AbstractBaseFoundation.timedEvent(AbstractBaseFoundation.java:126) ~[?:?]
        at space.arim.libertybans.core.AbstractBaseFoundation.startup(AbstractBaseFoundation.java:64) ~[?:?]
        at space.arim.libertybans.env.bungee.plugin.BungeePlugin.initialize(BungeePlugin.java:96) ~[?:?]
        at space.arim.libertybans.env.bungee.plugin.BungeePlugin.onEnable(BungeePlugin.java:46) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:316) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536]
        at net.md_5.bungee.BungeeCord.start(BungeeCord.java:299) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536]
        at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536]
        at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536]
Caused by: org.flywaydb.core.api.exception.FlywayValidateException: Validate failed: Migrations have failed validation
Detected failed migration to version 24 (Add applicable history view). Please remove any half-completed changes then run repair to fix the schema history.
Need more flexibility with validation rules? Learn more: https://rd.gt/3AbJUZE
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:131) ~[?:?]
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:124) ~[?:?]
        at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:214) ~[?:?]
        at org.flywaydb.core.Flyway.migrate(Flyway.java:124) ~[?:?]
        at space.arim.libertybans.core.database.flyway.MigrateWithFlyway.migrate(MigrateWithFlyway.java:46) ~[?:?]
        ... 12 more

**Comment by A248** [comment]
The most likely cause of the issue you are experiencing is that you forgot to grant full permissions to the SQL user. It is not an issue with LibertyBans, but I can help you fix your database configuration.

Please follow these steps to diagnose further.

1. Reset your database -- remove all tables belonging to LibertyBans (names starting with `libertybans_`).
2. Restart the server with LibertyBans installed
3. If there is another error, please copy and paste it exactly, and report it here. Do **not** restart the server again and use that error (it will be less informative) -- I need the **first** error you see after a fresh install of LibertyBans in order to help you.

Also, feel free to use Discord or Github, whichever is more convenient for you, since this has become a support request rather than a bug report.

**Comment by A248** [comment]
Because it's been two weeks and I haven't heard anything from you, I am closing this issue. However, you may still comment and I will respond if there's anything you need.
