### ISSUE TITLE
[Bug Report]: 

### ISSUE THREAD

**Issue by Uzuark** [A248/LibertyBans#220]
### LibertyBans Version

1.1.0-M3

### I have confirmed that ...

- [X] LibertyBans is up to date
- [x] No similar issue has been reported

### Platform

Velocity

### Description

[13:37:37 ERROR] [space.arim.libertybans.core.database.DatabaseSettings]: Unable to migrate your database. Please create a backup of your database and promptly report this issue.
space.arim.libertybans.core.database.flyway.MigrationFailedException: org.flywaydb.core.internal.exception.FlywaySqlException: Unable to check whether schema `minecraft_ban` is empty
-------------------------------------------------------
SQL State  : HY000
Error Code : 1728
Message    : (conn=158678) Cannot load from mysql.proc. The table is probably corrupted

        at space.arim.libertybans.core.database.flyway.MigrateWithFlyway.migrate(MigrateWithFlyway.java:48) ~[?:?]
        at space.arim.libertybans.core.database.DatabaseSettings.create(DatabaseSettings.java:119) ~[?:?]
        at space.arim.libertybans.core.database.DatabaseSettings.create(DatabaseSettings.java:77) ~[?:?]
        at space.arim.libertybans.core.database.DatabaseManager.startup(DatabaseManager.java:86) ~[?:?]
        at space.arim.libertybans.core.LifecycleGodfather.startup0(LifecycleGodfather.java:77) ~[?:?]
        at space.arim.libertybans.core.AbstractBaseFoundation.timedEvent(AbstractBaseFoundation.java:126) ~[?:?]
        at space.arim.libertybans.core.AbstractBaseFoundation.startup(AbstractBaseFoundation.java:64) ~[?:?]
        at space.arim.libertybans.env.velocity.plugin.VelocityPlugin.initialize(VelocityPlugin.java:110) ~[?:?]
        at space.arim.libertybans.env.velocity.plugin.VelocityPlugin.onProxyInitialize(VelocityPlugin.java:72) ~[?:?]
        at space.arim.libertybans.env.velocity.plugin.Lmbda$3.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:597) ~[velocity.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:478) ~[velocity.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1589) [?:?]
Caused by: org.flywaydb.core.internal.exception.FlywaySqlException: Unable to check whether schema `minecraft_ban` is empty
-------------------------------------------------------
SQL State  : HY000
Error Code : 1728
Message    : (conn=158678) Cannot load from mysql.proc. The table is probably corrupted

        at org.flywaydb.core.internal.database.base.Schema.empty(Schema.java:68) ~[?:?]
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:138) ~[?:?]
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:124) ~[?:?]
        at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:214) ~[?:?]
        at org.flywaydb.core.Flyway.migrate(Flyway.java:124) ~[?:?]
        at space.arim.libertybans.core.database.flyway.MigrateWithFlyway.migrate(MigrateWithFlyway.java:46) ~[?:?]
        ... 15 more
Caused by: java.sql.SQLException: (conn=158678) Cannot load from mysql.proc. The table is probably corrupted
        at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:299) ~[?:?]
        at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:370) ~[?:?]
        at org.mariadb.jdbc.client.result.Result.readNext(Result.java:176) ~[?:?]
        at org.mariadb.jdbc.client.result.StreamingResult.addStreamingValue(StreamingResult.java:124) ~[?:?]
        at org.mariadb.jdbc.client.result.StreamingResult.<init>(StreamingResult.java:92) ~[?:?]
        at org.mariadb.jdbc.message.ClientMessage.readPacket(ClientMessage.java:250) ~[?:?]
        at org.mariadb.jdbc.message.client.PrepareExecutePacket.readPacket(PrepareExecutePacket.java:184) ~[?:?]
        at org.mariadb.jdbc.client.impl.StandardClient.readPacket(StandardClient.java:855) ~[?:?]
        at org.mariadb.jdbc.client.impl.StandardClient.readResults(StandardClient.java:794) ~[?:?]
        at org.mariadb.jdbc.client.impl.StandardClient.execute(StandardClient.java:653) ~[?:?]
        at org.mariadb.jdbc.ServerPreparedStatement.executePipeline(ServerPreparedStatement.java:117) ~[?:?]
        at org.mariadb.jdbc.ServerPreparedStatement.executeInternal(ServerPreparedStatement.java:95) ~[?:?]
        at org.mariadb.jdbc.ServerPreparedStatement.executeQuery(ServerPreparedStatement.java:431) ~[?:?]
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52) ~[?:?]
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java) ~[?:?]
        at org.flywaydb.core.internal.jdbc.JdbcTemplate.queryForInt(JdbcTemplate.java:104) ~[?:?]
        at org.flywaydb.core.internal.database.mysql.MySQLSchema.doEmpty(MySQLSchema.java:46) ~[?:?]
        at org.flywaydb.core.internal.database.base.Schema.empty(Schema.java:66) ~[?:?]
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:138) ~[?:?]
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:124) ~[?:?]
        at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:214) ~[?:?]
        at org.flywaydb.core.Flyway.migrate(Flyway.java:124) ~[?:?]
        at space.arim.libertybans.core.database.flyway.MigrateWithFlyway.migrate(MigrateWithFlyway.java:46) ~[?:?]
        ... 15 more

**Comment by A248** [comment]
Hi, thanks for reporting. However, this is a problem with your database. If you search for "Cannot load from mysql.proc", you'll receive many web results. Running the `mariadb-upgrade` command will usually solve the issue.

If you need additional support, please feel free to join Discord or IRC. However, as it isn't a LibertyBans problem, I'll be closing this issue.
