### ISSUE TITLE
[Bug Report]: MariaDB connect issue

### ISSUE THREAD

**Issue by HulkHogan6262** [A248/LibertyBans#221]
### LibertyBans Version

LibertyBans 1.1.0-M3

### I have confirmed that ...

- [X] LibertyBans is up to date
- [X] No similar issue has been reported

### Platform

Velocity

### Description

Hello, I'm opening this issue to tell you about a problem I'm having with LibertyBans on my Velocity proxy. I want it to store its data in a MariaDB database provided by my hosting provider. I've changed the configuration without any problems, but when I start the proxy with the new configuration I get an error I don't understand
```[13:41:54 ERROR]: Couldn't pass ProxyInitializeEvent to libertybans
java.lang.NoClassDefFoundError: me/lucko/luckperms/lib/mariadb/client/SocketHelper (wrong name: org/mariadb/jdbc/client/SocketHelper)
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:524) ~[?:?]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:427) ~[?:?]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:421) ~[?:?]
        at java.security.AccessController.doPrivileged(AccessController.java:712) ~[?:?]
        at java.net.URLClassLoader.findClass(URLClassLoader.java:420) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass0(PluginClassLoader.java:70) ~[velocity.jar:3.2.0-SNAPSHOT (git-40b76c63-b256)]
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass0(PluginClassLoader.java:79) ~[velocity.jar:3.2.0-SNAPSHOT (git-40b76c63-b256)]
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:64) ~[velocity.jar:3.2.0-SNAPSHOT (git-40b76c63-b256)]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:574) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at org.mariadb.jdbc.client.impl.ConnectionHelper.connectSocket(ConnectionHelper.java:125) ~[?:?]
        at org.mariadb.jdbc.client.impl.StandardClient.<init>(StandardClient.java:99) ~[?:?]
        at org.mariadb.jdbc.Driver.connect(Driver.java:70) ~[?:?]
        at org.mariadb.jdbc.Driver.connect(Driver.java:101) ~[?:?]
        at org.mariadb.jdbc.Driver.connect(Driver.java:27) ~[?:?]
        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[?:?]
        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359) ~[?:?]
        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201) ~[?:?]
        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470) ~[?:?]
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561) ~[?:?]
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:100) ~[?:?]
        at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81) ~[?:?]
        at space.arim.libertybans.core.database.DatabaseSettings.createDataSource(DatabaseSettings.java:93) ~[?:?]
        at space.arim.libertybans.core.database.DatabaseSettings.create(DatabaseSettings.java:114) ~[?:?]
        at space.arim.libertybans.core.database.DatabaseSettings.create(DatabaseSettings.java:77) ~[?:?]
        at space.arim.libertybans.core.database.DatabaseManager.startup(DatabaseManager.java:86) ~[?:?]
        at space.arim.libertybans.core.LifecycleGodfather.startup0(LifecycleGodfather.java:77) ~[?:?]
        at space.arim.libertybans.core.AbstractBaseFoundation.timedEvent(AbstractBaseFoundation.java:126) ~[?:?]
        at space.arim.libertybans.core.AbstractBaseFoundation.startup(AbstractBaseFoundation.java:64) ~[?:?]
        at space.arim.libertybans.env.velocity.plugin.VelocityPlugin.initialize(VelocityPlugin.java:110) ~[?:?]
        at space.arim.libertybans.env.velocity.plugin.VelocityPlugin.onProxyInitialize(VelocityPlugin.java:72) ~[?:?]
        at space.arim.libertybans.env.velocity.plugin.Lmbda$5.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity.jar:3.2.0-SNAPSHOT (git-40b76c63-b256)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[velocity.jar:3.2.0-SNAPSHOT (git-40b76c63-b256)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[velocity.jar:3.2.0-SNAPSHOT (git-40b76c63-b256)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
```
        
Please help me solve this problem as soon as possible, as my Minecraft server opens in a few days. Thanks in advance.

**Comment by A248** [comment]
This is a bug in LuckPerms: https://github.com/LuckPerms/LuckPerms/issues/3681. Try updating LuckPerms because it was supposed to be fixed.

If it still doesn't work, send me the full console output, and then you have a few alternative solutions:
1.) Downgrade LuckPerms to [v5.4.76](https://ci.lucko.me/job/LuckPerms/1488/)
2.) Get LuckPerms to fix the bug
3.) Switch from MariaDB to HSQLDB. Later, after LuckPerms fixes the bug, you can transfer your data from HSQLDB to MariaDB using LibertyBans' built-in converter.

Issue #213 has more information

**Comment by A248** [comment]
I'm closing this issue, but feel free to join Discord or IRC if you need more assistance
