### ISSUE TITLE
[Bug Report]: Error MariaDB

### ISSUE THREAD

**Issue by frogglen** [A248/LibertyBans#233]
### LibertyBans Version

LibertyBans_1.1.0-SNAPSHOT.jar  Build #138

### I have confirmed that ...

- [X] LibertyBans is up to date
- [X] No similar issue has been reported

### Platform

Spigot/Paper

### Description

[16:16:40 INFO]: [com.zaxxer.hikari.HikariDataSource] LibertyBansPool-MariaDB - Starting...
[16:16:41 INFO]: [com.zaxxer.hikari.pool.HikariPool] LibertyBansPool-MariaDB - Added connection org.mariadb.jdbc.Connection@355b5c73
[16:16:41 INFO]: [com.zaxxer.hikari.HikariDataSource] LibertyBansPool-MariaDB - Start completed.
[16:16:41 WARN]: [space.arim.libertybans.core.database.DatabaseRequirements] You are using MariaDB version 10.3. This database version is old and only supported for retrograde compatibility. It is strongly recommended to update your database to at least version 10.6. Support may be dropped for version 10.3 in the future.
[16:16:42 INFO]: [org.flywaydb.core.internal.license.VersionPrinter] Flyway Community Edition 8.2.0 by Redgate
[16:16:42 INFO]: [org.flywaydb.core.internal.database.base.BaseDatabaseType] Database: jdbc:mariadb://cayman.teramont.net (MariaDB 10.3)
[16:16:42 INFO]: [org.flywaydb.core.internal.command.DbValidate] Successfully validated 14 migrations (execution time 00:00.202s)
[16:16:42 INFO]: [org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory] Creating Schema History table `s658_libertybans`.`libertybans_schema_history` ...
[16:16:42 INFO]: [org.flywaydb.core.internal.command.DbMigrate] Current version of schema `s658_libertybans`: << Empty Schema >>
[16:16:42 INFO]: [org.flywaydb.core.internal.command.DbMigrate] Migrating schema `s658_libertybans` to version "1 - Principle"
[16:16:47 INFO]: [org.flywaydb.core.internal.command.DbMigrate] Migrating schema `s658_libertybans` to version "2 - Create tables for names addresses"
[16:16:47 INFO]: [org.flywaydb.core.internal.command.DbMigrate] Migrating schema `s658_libertybans` to version "4 - Create tables for punishments"
[16:16:48 INFO]: [org.flywaydb.core.internal.command.DbMigrate] Migrating schema `s658_libertybans` to version "8 - Create views for punishments"
[16:16:48 INFO]: [org.flywaydb.core.internal.command.DbMigrate] Migrating schema `s658_libertybans` to version "16 - Complete migration from 08x"
[16:16:48 INFO]: [org.flywaydb.core.internal.command.DbMigrate] Migrating schema `s658_libertybans` to version "20 - Stricter data integrity checks"
[16:16:48 INFO]: [org.flywaydb.core.internal.command.DbMigrate] Migrating schema `s658_libertybans` to version "24 - Add applicable history view"
[16:16:48 INFO]: [org.flywaydb.core.internal.command.DbMigrate] Migrating schema `s658_libertybans` to version "28 - Positive duration guarantee"
[16:16:48 INFO]: [org.flywaydb.core.internal.command.DbMigrate] Migrating schema `s658_libertybans` to version "31 - Track identifier sequence"
[16:16:48 INFO]: [org.flywaydb.core.internal.command.DbMigrate] Migrating schema `s658_libertybans` to version "32 - Escalation tracks"
[16:16:48 INFO]: [org.flywaydb.core.internal.command.DbMigrate] Migrating schema `s658_libertybans` to version "34 - Scope identifier sequence"
[16:16:48 INFO]: [org.flywaydb.core.internal.command.DbMigrate] Migrating schema `s658_libertybans` to version "36 - Server scopes"
[16:16:49 INFO]: [org.flywaydb.core.internal.command.DbMigrate] Migrating schema `s658_libertybans` to version "38 - Scope migration"
[16:16:50 INFO]: [org.flywaydb.core.internal.command.DbMigrate] Migrating schema `s658_libertybans` with repeatable migration "Set Revision"
[16:16:50 INFO]: [org.flywaydb.core.internal.command.DbMigrate] Successfully applied 14 migrations to schema `s658_libertybans`, now at version v38 (execution time 00:07.341s)
[16:16:50 INFO]: [space.arim.libertybans.core.database.jooq.JooqClassloading] Finished pre-initializing classes in 0.16 seconds
[16:16:50 ERROR]: Error occurred while enabling LibertyBans v1.1.0-SNAPSHOT-2023-09-17T12:53:24Z (Is it up to date?)
java.util.concurrent.CompletionException: space.arim.dazzleconf.error.IllDefinedConfigException: Encountered an error while loading the configuration. 
Reason: No ValueSerialiser was found for interface space.arim.libertybans.api.scope.ServerScope at entry scope. To use custom types, a relevant ValueSerialiser must exist.
(This is an error on behalf of the developer)
Extra info: None
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1311) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1841) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1806) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177) ~[?:?]
Caused by: space.arim.dazzleconf.error.IllDefinedConfigException: Encountered an error while loading the configuration. 
Reason: No ValueSerialiser was found for interface space.arim.libertybans.api.scope.ServerScope at entry scope. To use custom types, a relevant ValueSerialiser must exist.
(This is an error on behalf of the developer)
Extra info: None
        at space.arim.dazzleconf.internal.error.DeveloperError.toConfigException(DeveloperError.java:72) ~[LibertyBans-ClassLoader:?]
        at space.arim.dazzleconf.internal.processor.FlexibleTypeImpl.getSerialiser(FlexibleTypeImpl.java:326) ~[LibertyBans-ClassLoader:?]
        at space.arim.dazzleconf.internal.processor.FlexibleTypeImpl.getObject0(FlexibleTypeImpl.java:319) ~[LibertyBans-ClassLoader:?]
        at space.arim.dazzleconf.internal.processor.FlexibleTypeImpl.getObject(FlexibleTypeImpl.java:275) ~[LibertyBans-ClassLoader:?]
        at space.arim.dazzleconf.internal.processor.Composition.processObject(Composition.java:89) ~[LibertyBans-ClassLoader:?]
        at space.arim.dazzleconf.internal.processor.ProcessorBase.getProcessedValue(ProcessorBase.java:126) ~[LibertyBans-ClassLoader:?]
        at space.arim.dazzleconf.internal.processor.ProcessorBase.process(ProcessorBase.java:97) ~[LibertyBans-ClassLoader:?]
        at space.arim.dazzleconf.internal.processor.ProcessorBase.createConfig(ProcessorBase.java:71) ~[LibertyBans-ClassLoader:?]
        at space.arim.dazzleconf.internal.processor.ProcessorBase.createFromProcessor(ProcessorBase.java:160) ~[LibertyBans-ClassLoader:?]
        at space.arim.dazzleconf.internal.processor.MapProcessor.createChildConfig(MapProcessor.java:60) ~[LibertyBans-ClassLoader:?]
        at space.arim.dazzleconf.internal.processor.ProcessorBase.createNested(ProcessorBase.java:156) ~[LibertyBans-ClassLoader:?]
        at space.arim.dazzleconf.internal.processor.Composition.lambda$getMap$2(Composition.java:143) ~[LibertyBans-ClassLoader:?]
        at space.arim.dazzleconf.internal.processor.FlexibleTypeImpl.getMap(FlexibleTypeImpl.java:256) ~[LibertyBans-ClassLoader:?]
        at space.arim.dazzleconf.internal.processor.Composition.getMap(Composition.java:159) ~[LibertyBans-ClassLoader:?]
        at space.arim.dazzleconf.internal.processor.Composition.processObject(Composition.java:71) ~[LibertyBans-ClassLoader:?]
        at space.arim.dazzleconf.internal.processor.ProcessorBase.getProcessedValue(ProcessorBase.java:126) ~[LibertyBans-ClassLoader:?]
        at space.arim.dazzleconf.internal.processor.ProcessorBase.process(ProcessorBase.java:97) ~[LibertyBans-ClassLoader:?]
        at space.arim.dazzleconf.internal.processor.ProcessorBase.createConfig(ProcessorBase.java:71) ~[LibertyBans-ClassLoader:?]
        at space.arim.dazzleconf.factory.ConfigurationFormatFactory.fromRawMap(ConfigurationFormatFactory.java:174) ~[LibertyBans-ClassLoader:?]
        at space.arim.dazzleconf.factory.ConfigurationFormatFactory.load(ConfigurationFormatFactory.java:126) ~[LibertyBans-ClassLoader:?]
        at space.arim.dazzleconf.factory.DelegatingConfigurationFactory.load(DelegatingConfigurationFactory.java:57) ~[LibertyBans-ClassLoader:?]
        at space.arim.dazzleconf.factory.AbstractConfigurationFactory.load(AbstractConfigurationFactory.java:42) ~[LibertyBans-ClassLoader:?]
        at space.arim.libertybans.core.config.ConfigHolder.loadFromPath(ConfigHolder.java:116) ~[LibertyBans-ClassLoader:?]
        at space.arim.libertybans.core.config.ConfigHolder.lambda$reload$0(ConfigHolder.java:87) ~[LibertyBans-ClassLoader:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        ... 6 more
[16:16:50 INFO]: [LibertyBans] Disabling LibertyBans v1.1.0-SNAPSHOT-2023-09-17T12:53:24Z
[16:16:50 WARN]: [LibertyBans] LibertyBans wasn't launched; check your log for a startup error

**Comment by A248** [comment]
Please update your addon jars. The addon jars should be kept in-sync with the LibertyBans version.

This is not a bug with LibertyBans or related to MariaDB; it only looks like MariaDB is related because the log messages happen at the same time.
