### ISSUE TITLE
[Bug Report]: Incompatibility with Velocity-CTD

### ISSUE THREAD

**Issue by HonzasikCZ** [A248/LibertyBans#275]
### LibertyBans Version

LibertyBans 1.1.0-RC2

### I have confirmed that ...

- [x] LibertyBans is up to date
- [X] No similar issue has been reported

### Platform

Velocity

### Description

```
[00:30:10] [main/ERROR] [com.velocitypowered.proxy.plugin.VelocityPluginManager]: Can't create plugin libertybans
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) [Guice/MissingConstructor]: No injectable constructor for type VelocityPlugin.

class VelocityPlugin does not have a @Inject annotated constructor or a no-arg constructor.

Requested by:
1  : VelocityPlugin.class(VelocityPlugin.java:60)
     at VelocityPluginModule.configure(VelocityPluginModule.java:47)

Learn more:
  https://github.com/google/guice/wiki/MISSING_CONSTRUCTOR

1 error

======================
Full classname legend:
======================
VelocityPlugin:       "space.arim.libertybans.env.velocity.plugin.VelocityPlugin"
VelocityPluginModule: "com.velocitypowered.proxy.plugin.loader.java.VelocityPluginModule"
========================
End of classname legend:
========================

	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:589) ~[server.jar:3.3.0-SNAPSHOT (git-1a47a4c6)]
	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:163) ~[server.jar:3.3.0-SNAPSHOT (git-1a47a4c6)]
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110) ~[server.jar:3.3.0-SNAPSHOT (git-1a47a4c6)]
	at com.google.inject.Guice.createInjector(Guice.java:87) ~[server.jar:3.3.0-SNAPSHOT (git-1a47a4c6)]
	at com.google.inject.Guice.createInjector(Guice.java:69) ~[server.jar:3.3.0-SNAPSHOT (git-1a47a4c6)]
	at com.google.inject.Guice.createInjector(Guice.java:59) ~[server.jar:3.3.0-SNAPSHOT (git-1a47a4c6)]
	at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.createPlugin(JavaPluginLoader.java:129) ~[server.jar:3.3.0-SNAPSHOT (git-1a47a4c6)]
	at com.velocitypowered.proxy.plugin.VelocityPluginManager.loadPlugins(VelocityPluginManager.java:168) ~[server.jar:3.3.0-SNAPSHOT (git-1a47a4c6)]
	at com.velocitypowered.proxy.VelocityServer.loadPlugins(VelocityServer.java:420) ~[server.jar:3.3.0-SNAPSHOT (git-1a47a4c6)]
	at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:260) ~[server.jar:3.3.0-SNAPSHOT (git-1a47a4c6)]
	at com.velocitypowered.proxy.Velocity.main(Velocity.java:71) ~[server.jar:3.3.0-SNAPSHOT (git-1a47a4c6)]
[00:30:10] [main/INFO] [com.velocitypowered.proxy.plugin.VelocityPluginManager]: Loaded plugin protocolize v2 by Exceptionflug
[00:30:10] [main/INFO] [com.velocitypowered.proxy.plugin.VelocityPluginManager]: Loaded plugin nanolimbovelocity 1.0.11 by bivashy, Nan1t
```

**Comment by A248** [comment]
I spent a lot of time trying to find where Velocity made a breaking change. Are you using a different version of Velocity? I can't find the commit listed in the stack trace (1a47a4c6) anywhere among Velocity's past builds.

**Comment by HonzasikCZ** [comment]
Im using [Velocity-CTD](https://github.com/GemstoneGG/Velocity-CTD)

**Comment by A248** [comment]
Okay then. Here's the bug. Velocity-CTD should revert this commit to restore compatibility:

https://github.com/GemstoneGG/Velocity-CTD/commit/95f24d62c52285bc16241dd21ad96cd75825d41a
