### ISSUE TITLE
[Bug Report]: Throw error with BukkitOfUtils

### ISSUE THREAD

**Issue by lamya3** [A248/LibertyBans#281]
### LibertyBans Version

LibertyBans_Release-1.1.0-RC2

### I have confirmed that ...

- [X] LibertyBans is up to date
- [X] No similar issue has been reported

### Platform

Spigot/Paper ([LeavesMC](https://github.com/LeavesMC/Leaves))

### Description
Related plugin: LibertyBans_Release-1.1.0-RC2 + [BukkitOfUtils v1.40.1](https://modrinth.com/plugin/bukkitofutils/version/j2fSFHR0)
Hi, there are something errors when I load BukkitOfUtils + LibertyBans，here's the console error massages:
```
[01:00:27 INFO]: [BukkitOfUtils] Enabling BukkitOfUtils v1.4.1*
[01:00:27 INFO]: [BukkitOfUtils] [INFO] TaskManager is now initialized!
[01:00:27 INFO]: [BukkitOfUtils] [INFO] Callback Listener has been registered!
[01:00:27 INFO]: [BukkitOfUtils] [INFO] > [console] FireString Registered!
[01:00:27 INFO]: [BukkitOfUtils] [INFO] > [player] FireString Registered!
[01:00:27 INFO]: [BukkitOfUtils] [INFO] > [consolechat] FireString Registered!
[01:00:27 INFO]: [BukkitOfUtils] [INFO] > [playerchat] FireString Registered!
[01:00:27 INFO]: [BukkitOfUtils] [INFO] > [message] FireString Registered!
[01:00:27 INFO]: [BukkitOfUtils] [INFO] > [title] FireString Registered!
[01:00:27 INFO]: [BukkitOfUtils] [INFO] > [broadcast] FireString Registered!
[01:00:27 INFO]: [BukkitOfUtils] [INFO] > [broadcasttitle] FireString Registered!
[01:00:27 INFO]: [BukkitOfUtils] [INFO] Initialized FireStringManager with 8 FireStrings
[01:00:27 INFO]: [Pacifism] Enabling Pacifism v1.10.0*
[01:00:27 INFO]: [tv.quaint.thebase.lib.hikari.HikariDataSource] Pacifism - Pool - Starting...
[01:00:27 INFO]: [tv.quaint.thebase.lib.hikari.pool.HikariPool] Pacifism - Pool - Added connection org.sqlite.jdbc4.JDBC4Connection@28f96a0
[01:00:27 INFO]: [tv.quaint.thebase.lib.hikari.HikariDataSource] Pacifism - Pool - Start completed.
[01:00:27 INFO]: [LibertyBans] Enabling LibertyBans v1.1.0-RC2
[01:00:27 INFO]: [LibertyBans] No addons detected
[01:00:27 INFO]: [space.arim.libertybans.core.addon.AddonLoader] No addons loaded
[01:00:28 INFO]: [space.arim.libertybans.core.AbstractBaseFoundation] Conducting start phase...
[01:00:28 ERROR]: Error occurred while enabling LibertyBans v1.1.0-RC2 (Is it up to date?)
java.lang.NoSuchMethodError: 'boolean org.bukkit.Server.isGlobalTickThread()'
        at space.arim.morepaperlib.scheduling.GracefulScheduling.isOnGlobalRegionThread(GracefulScheduling.java:146) ~[LibertyBans-ClassLoader:?]
        at space.arim.api.env.bukkit.BukkitFactoryOfTheFutureImpl.isPrimaryThread0(BukkitFactoryOfTheFutureImpl.java:59) ~[LibertyBans-ClassLoader:?]
        at space.arim.api.env.concurrent.MainThreadCachingFutureFactory.isPrimaryThread(MainThreadCachingFutureFactory.java:49) ~[LibertyBans-ClassLoader:?]
        at space.arim.api.env.bukkit.BukkitFactoryOfTheFutureImpl.create(BukkitFactoryOfTheFutureImpl.java:53) ~[LibertyBans-ClassLoader:?]
        at space.arim.api.env.bukkit.BukkitFactoryOfTheFuture.create(BukkitFactoryOfTheFuture.java:56) ~[LibertyBans-ClassLoader:?]
        at space.arim.api.env.bukkit.BukkitFactoryOfTheFuture.create(BukkitFactoryOfTheFuture.java:45) ~[LibertyBans-ClassLoader:?]
        at space.arim.api.env.bukkit.BukkitPlatformHandleImpl.createFuturesFactory(BukkitPlatformHandle.java:64) ~[LibertyBans-ClassLoader:?]
        at java.util.Optional.orElseGet(Optional.java:364) ~[?:?]
        at space.arim.libertybans.core.service.StandardAsynchronicityManager.startup(StandardAsynchronicityManager.java:90) ~[LibertyBans-ClassLoader:?]
        at space.arim.libertybans.core.LifecycleGodfather.startup0(LifecycleGodfather.java:75) ~[LibertyBans-ClassLoader:?]
        at space.arim.libertybans.core.AbstractBaseFoundation.timedEvent(AbstractBaseFoundation.java:126) ~[LibertyBans-ClassLoader:?]
        at space.arim.libertybans.core.AbstractBaseFoundation.startup(AbstractBaseFoundation.java:64) ~[LibertyBans-ClassLoader:?]
        at space.arim.libertybans.env.spigot.plugin.SpigotPlugin.initialize(SpigotPlugin.java:112) ~[LibertyBans_Release-1.1.0-RC2.jar:?]
        at space.arim.libertybans.env.spigot.plugin.SpigotPlugin.onEnable(SpigotPlugin.java:48) ~[LibertyBans_Release-1.1.0-RC2.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[leaves-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[leaves-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:649) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:560) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:629) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:426) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:313) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1095) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:309) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[01:00:28 INFO]: [LibertyBans] Disabling LibertyBans v1.1.0-RC2
[01:00:28 WARN]: [LibertyBans] LibertyBans wasn't launched; check your log for a startup error
```
before I post this issue, I have contacted the developers of BukkitOfUtils. He gave some advice about that. Please review the issue :[throw warning when players join #6](https://github.com/ProjectsForAll/Pacifism/issues/6#issuecomment-2365225132)

**Comment by A248** [comment]
This is a bug of BukkitOfUtils, which is shading the entire Folia server platform into its plugin jar. This bug makes LibertyBans -- and potentially other plugins, I don't know -- think that it is operating on the Folia server platform.

The Folia Java classes don't belong to BukkitOfUtils, so BukkitOfUtils shouldn't be shading them. They will need to fix this bug on their end.

I know this because I downloaded BukkitOfUtils' plugin jar and unzipped its contents. CC @MrDrakify
