### ISSUE TITLE
UltimateTeams shading Folia library causes LibertyBans to break

### ISSUE THREAD

**Issue by HonzasikCZ** [A248/LibertyBans#283]
### LibertyBans Version

LibertyBans 1.1.0-RC2

### I have confirmed that ...

- [X] LibertyBans is up to date
- [X] No similar issue has been reported

### Platform

Spigot/Paper

### Description

When the server is turned on, when LibertyBans is started, an error is displayed in the console and the plugin is disabled

ERROR:
```
21:12:56[INFO] [space.arim.libertybans.core.AbstractBaseFoundation] Conducting start phase...
21:12:56[ERROR] Error occurred while enabling LibertyBans v1.1.0-RC2 (Is it up to date?)
java.lang.NoSuchMethodError: 'boolean org.bukkit.Server.isGlobalTickThread()'
at space.arim.morepaperlib.scheduling.GracefulScheduling.isOnGlobalRegionThread(GracefulScheduling.java:146) ~[UltimateTeams-2.2.jar:?]
at space.arim.api.env.bukkit.BukkitFactoryOfTheFutureImpl.isPrimaryThread0(BukkitFactoryOfTheFutureImpl.java:59) ~[LibertyBans-ClassLoader:?]
at space.arim.api.env.concurrent.MainThreadCachingFutureFactory.isPrimaryThread(MainThreadCachingFutureFactory.java:49) ~[LibertyBans-ClassLoader:?]
at space.arim.api.env.bukkit.BukkitFactoryOfTheFutureImpl.create(BukkitFactoryOfTheFutureImpl.java:53) ~[LibertyBans-ClassLoader:?]
at space.arim.api.env.bukkit.BukkitFactoryOfTheFuture.create(BukkitFactoryOfTheFuture.java:56) ~[LibertyBans-ClassLoader:?]
at space.arim.api.env.bukkit.BukkitFactoryOfTheFuture.create(BukkitFactoryOfTheFuture.java:45) ~[LibertyBans-ClassLoader:?]
at space.arim.api.env.bukkit.BukkitPlatformHandleImpl.createFuturesFactory(BukkitPlatformHandle.java:64) ~[LibertyBans-ClassLoader:?]
at java.util.Optional.orElseGet(Unknown Source) ~[?:?]
at space.arim.libertybans.core.service.StandardAsynchronicityManager.startup(StandardAsynchronicityManager.java:90) ~[LibertyBans-ClassLoader:?]
at space.arim.libertybans.core.LifecycleGodfather.startup0(LifecycleGodfather.java:75) ~[LibertyBans-ClassLoader:?]
at space.arim.libertybans.core.AbstractBaseFoundation.timedEvent(AbstractBaseFoundation.java:126) ~[LibertyBans-ClassLoader:?]
at space.arim.libertybans.core.AbstractBaseFoundation.startup(AbstractBaseFoundation.java:64) ~[LibertyBans-ClassLoader:?]
at space.arim.libertybans.env.spigot.plugin.SpigotPlugin.initialize(SpigotPlugin.java:112) ~[LibertyBans_Release-1.1.0-RC2.jar:?]
at space.arim.libertybans.env.spigot.plugin.SpigotPlugin.onEnable(SpigotPlugin.java:48) ~[LibertyBans_Release-1.1.0-RC2.jar:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[purpur-1.20.4.jar:git-Purpur-2176]
at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.4.jar:git-Purpur-2176]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:653) ~[purpur-1.20.4.jar:git-Purpur-2176]
at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:564) ~[purpur-1.20.4.jar:git-Purpur-2176]
at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675) ~[purpur-1.20.4.jar:git-Purpur-2176]
at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435) ~[purpur-1.20.4.jar:git-Purpur-2176]
at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:346) ~[purpur-1.20.4.jar:git-Purpur-2176]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1146) ~[purpur-1.20.4.jar:git-Purpur-2176]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2176]
at java.lang.Thread.run(Unknown Source) ~[?:?]
21:12:56[INFO] [LibertyBans] Disabling LibertyBans v1.1.0-RC2
```

**Comment by Nadwey** [comment]
Update Ultimate Teams to at least v2.4

**Comment by HonzasikCZ** [comment]
Yes its working!!! Thanks!!
